apps/login_app/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'register$', views.register, name='register'),
    url(r'login$', views.login, name='login'),
    url(r'^logout$', views.logout, name='logout')
]

apps/travel_app/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.index, name="index"),
    url(r'^add$', views.add, name="add" ),
    url(r'^process$', views.process, name='process'),
    url(r'^logout$', views.logout, name='logout'),
    url(r'^destination/(?P<trip_id>\d+)$', views.destination, name='destination'),
    url(r'^destination/join/(?P<trip_id>\d+)$', views.join, name='join')
]

travel_buddy/urls.py
from django.conf.urls import url, include

urlpatterns = [
    url(r'^', include('apps.login_app.urls', namespace="login")),
    url(r'^travel', include('apps.travel_app.urls', namespace="travel")),
]

apps/login_app/models.py
from __future__ import unicode_literals
from django.db import models
import bcrypt

class UserManager(models.Manager):
    def register(self, input):
        errors = []

        if len(input['first_name']) < 2:
            errors.append('Must have at least 3 characters for name')

        if len(input['username']) < 2:
            errors.append('Must have at least 3 characters for username')

        if not input['first_name'].isalpha():
            errors.append('Your name can only contain letters')

        if input['password'] != input['password_confirm']:
            errors.append('Passwords do not match. Try again')

        if len(input['password']) < 8:
            errors.append('Must have at least 8 characters for password')

        same = User.objects.filter(username=input['username'])

        if same:
            errors.append('Username already exists')

        if len(errors) == 0:
            pwHash = bcrypt.hashpw(input['password'].encode(), bcrypt.gensalt().encode())
            user = User.objects.create(first_name=input['first_name'], username=input['username'], password=pwHash)
            return (True, user)

        else:
            return (False, errors)

    def login(self, input):
        errors = []
        user = User.objects.filter(username=input['username'])
        if user.exists():
            InputPw = input['password'].encode()
            HashPw = user[0].password.encode()

            if bcrypt.checkpw(InputPw, HashPw):
                return (True, user[0])
            else:
                errors.append(("Username or password is wrong"))
        else:
            errors.append(("Username or password is wrong"))
        return (False, errors)

class User(models.Model):
    first_name = models.CharField(max_length=50)
    username = models.CharField(max_length=100)
    password = models.CharField(max_length=100)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    objects = UserManager()

apps/travel_app/models.py
from __future__ import unicode_literals
from django.db import models
from datetime import datetime
from ..login_app.models import User

# Create your models here.
class TripManager(models.Manager):
    def addTrip(self, input, user):
        errors = []

        if len(input['destination']) == 0 or len(input['plan']) == 0 or len(input['start_date']) == 0 or len(input['end_date']) == 0:
            errors.append('Please do not leave any fields empty')

        if len(input['start_date']) > 0 or len(input['end_date']) > 0:
            start_date = datetime.strptime(input['start_date'], "%Y-%m-%d")
            end_date = datetime.strptime(input['end_date'], "%Y-%m-%d")

            if datetime.today() >= start_date:
                errors.append('Your start date must be today or later')
            if start_date > end_date:
                errors.append('Your end date cannot be earlier than today')

        if len(errors) == 0:
            trip = Trip.objects.create(destination=input['destination'], plan=input['plan'], user=user, start_date=start_date, end_date=end_date)
            trip.group.add(user)
            return (True, 'Your trip has been scheduled')

        else:
            return (False, errors)

    def joinTrip(self, trip_id, user):
        trip = Trip.objects.get(id=trip_id)
        trip.group.add(user)
        return (True, "You have joined the trip")


class Trip(models.Model):
    destination = models.CharField(max_length=50)
    plan = models.CharField(max_length=100)
    start_date = models.DateField()
    end_date = models.DateField()
    user = models.ForeignKey(User)
    group = models.ManyToManyField(User, related_name='travel')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    objects = TripManager()

apps/login_app/views.py
from django.shortcuts import render, redirect
from .models import User
from django.contrib import messages
from django.core.urlresolvers import reverse

# Create your views here.
def index(request):
    if 'user_id' in request.session:
        return redirect(reverse('travel:index'))
    else:
        return render(request, 'login_app/index.html')

def register(request):
    result = User.objects.register(request.POST)
    if result[0] == True:
        request.session['user_id'] = result[1].id
        messages.success(request, "You have successfully registered")
        return redirect(reverse('login:index'))
    else:
        for error in result[1]:
            messages.error(request, error)
        return redirect(reverse('login:index'))

def login(request):
    result = User.objects.login(request.POST)
    if result[0] == True:
        request.session['user_id'] = result[1].id
        return redirect(reverse('travel:index'))
    else:
        for error in result[1]:
            messages.error(request, error)
        return redirect(reverse('login:index'))

def logout(request):
    if 'user_id' in request.session:
        del request.session['user_id']
        messages.success(request, "You have successfully logged out")
        return redirect(reverse('login:index'))

apps/travel_app/views.py
from django.shortcuts import render, redirect, HttpResponse
from ..login_app.models import User
from .models import Trip
from django.core.urlresolvers import reverse
from django.contrib import messages

# Create your views here.
def index(request):
    if 'user_id' in request.session:
        user = User.objects.get(id=request.session['user_id'])
        context = {
            'data': user,
            'trips': Trip.objects.all().filter(group=user),
            'users': Trip.objects.all().exclude(group=user)
        }
        return render(request, 'travel_app/index.html', context)
    else:
        return redirect(reverse('login:index'))

def add(request):
    return render(request, 'travel_app/add.html')

def process(request):
    if request.method == 'POST':
        user = User.objects.get(id=request.session['user_id'])
        result = Trip.objects.addTrip(request.POST, user)
        if result[0] == True:
            messages.success(request, result[1])
            return redirect(reverse('travel:index'))
        else:
            for error in result[1]:
                messages.error(request, error)
            return redirect(reverse('travel:add'))

def destination(request, trip_id):
    trip = Trip.objects.get(id=trip_id)
    context = {
        'trips': trip,
        'group': trip.group.all()
    }
    return render(request,'travel_app/destination.html', context)

def join(request, trip_id):
    user = User.objects.get(id=request.session['user_id'])
    result = Trip.objects.joinTrip(trip_id, user)
    messages.success(request, result[1])
    return redirect(reverse('travel:index'))

def logout(request):
    request.session.clear()
    return redirect(reverse('login:index'))

apps/login_app/templates/login_app/index.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>Login and Registration</title>
    {% load staticfiles %}
  </head>
  <body>
    <h1>Welcome!</h1>
    <div id="wrapper">
      <div class="message">
        {% if messages %}
            {% for message in messages %}
                <li>{{message}}</li>
            {% endfor %}
        {% endif %}
      </div>

      <div class="register">
        <h3>Register</h3>
        <form class="ui form" action="{% url 'login:register' %}" method="post">
          {% csrf_token %}
          Name: <input type="text" name="first_name" placeholder="First Name">
          Userame: <input type="text" name="username" placeholder="Userame">
          Password: <input type="password" name="password" placeholder="Password">
          Confirm Password: <input type="password" name="password_confirm" placeholder="Confirm Password">
          <input type="submit" value="Register">
        </form>
      </div>

      <div class="login">
        <h3>Login</h3>
        <form class="ui form" action="{% url 'login:login' %}" method="post">
          {% csrf_token %}
          Userame: <input type="text" name="username" placeholder="Userame">
          Password: <input type="password" name="password" placeholder="Password">
          <input type="submit" value="Login">
        </form>
      </div>
    </div>
  </body>
</html>

apps/login_app/templates/login_app/success.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Success!</title>
  </head>
  <body>
    <h1>Hello! You have successfully logged in!</h1>
    <a href="/">Logout</a>
  </body>
</html>

apps/travel_app/templates/travel_app/add.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Add a Trip</title>
  </head>

  <body>
    {% if messages %}
        <ul>
        {% for message in messages %}
            <li>{{message}}</li>
        {% endfor %}
        </ul>
    {% endif %}

    <div>
      <h1>Add a Trip</h1>
      <form class="ui form" action="{% url 'travel:process' %}" method="post">
        {% csrf_token %}
        Destinaton: <input type="text" name="destination" placeholder="Destination">
        Description: <input type="text" name="plan" placeholder="Description">
        Travel Date From: <input type="date" name="start_date">
        Travel Date To: <input type="date" name="end_date"><br>
        <input type="submit" value="Add"><br>
        <a href="{% url 'travel:index' %}">Home</a><br>
        <a href="{% url 'login:logout' %}">Logout</a>
      </form>
    </div>
  </body>
</html>

apps/travel_app/templates/travel_app/destination.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Destination</title>
  </head>
  <body>

    {% if messages %}
        <ul>
        {% for message in messages %}
            <li>{{message}}</li>
        {% endfor %}
        </ul>
    {% endif %}

    {% if trips %}
    <h1>{{trips.destination}}</h1>
    <h3>Planned By: {{trips.user.first_name}}</h3>
    <h3>Travel Date From: {{trips.start_date}}</h3>
    <h3>Travel Date To: {{trips.end_date}}</h3><br>
    {% endif %}

<h1>Other users' joining the trip:</h1>
  {% for other in group %}
    <h3>{{other.first_name}}</h3>
  {% endfor %}

    <a href="{% url 'travel:index' %}">Home</a>
    <a href="{% url 'login:logout' %}">Logout</a>
  </body>
</html>

apps/travel_app/templates/travel_app/index.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Travel Buddy Main</title>
  </head>
  <body>
    <h1>Hello, {{data.first_name}}!</h1>

    {% if messages %}
        <ul>
        {% for message in messages %}
            <li>{{message}}</li>
        {% endfor %}
        </ul>
    {% endif %}

    <a href="/logout"><button>Log Out</button></a>
    <h3>Your Trip Schedules</h3>
    <table>
      <thead>
        <tr>
          <th>Destination</th>
          <th>Travel Start Date</th>
          <th>Travel End Date</th>
          <th>Plan</th>
        </tr>
      </thead>
      <tbody>
        {% for trip in trips %}
        <tr>
          <td><a href="{% url 'travel:destination' trip.id %}">{{trip.destination}}</a></td>
          <td>{{trip.start_date}}</td>
          <td>{{trip.end_date}}</td>
          <td>{{trip.plan}}</td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
    <a href="{% url 'travel:add' %}">Add Travel Plan</a>


    <h3>Other User's Travel Plans</h3>
    <table>
      <thead>
        <tr>
          <th>Name</th>
          <th>Destination</th>
          <th>Travel Start Date</th>
          <th>Travel End Date</th>
          <th>Do You Want to Join?</th>
        </tr>
      </thead>
      <tbody>
        {% for user in users %}
        <tr>
          <td>{{user.user.first_name}}</td>
          <td><a href="{% url 'travel:destination' user.id %}">{{user.destination}}</a></td>
          <td>{{user.start_date}}</td>
          <td>{{user.end_date}}</td>
          <td><a href="{% url 'travel:join' user.id %}">JOIN</td>
        </tr>
        {% endfor %}
      </tbody>
    </table>

  </body>
</html>